# frozen_string_literal: true

# Remove from a derived static archive every member that is byte-identical
# to a member of the base archive it bundles.
#
# Why: cargo's staticlib bundling packs the full native dependency closure
# into libtebako_driver.a (the driver's crate graph includes tfs), so the
# driver archive ships every member libtfs.a already carries — the same
# objects, byte for byte. The factory links BOTH archives; GNU ld tolerates
# the duplicate definitions (first wins) but Apple ld does not — ld_prime
# asserts (atomShouldReplaceExisting, "malformed atom files with duplicate
# names") and ld_classic errors "duplicate symbol" (the 0.16.3-era macos
# x86_64 legs). Deduping the driver against tfs.a keeps exactly the
# driver's own members; the pair then links clean on every host linker.
#
# Members are matched by (name, content) — never by name alone, so a
# name-shared member whose content differs is kept. The rewrite re-archives
# from the parsed bytes (never `ar x`: an archive may hold several members
# under one name) and rebuilds the symbol table with ranlib.
class ArCrossDeduper
  HEADER = 60

  def initialize(ar: "ar", ranlib: "ranlib")
    @ar = ar
    @ranlib = ranlib
  end

  # Drop from +derived+ every member byte-identical to one in +base+.
  # Returns the number of members dropped (0 = archive untouched).
  def dedupe(base, derived)
    base_keys = members_of(base).map { |m| key(m) }.to_set
    members = members_of(derived)
    kept = members.reject { |m| base_keys.include?(key(m)) }
    dropped = members.size - kept.size
    repack(derived, kept) if dropped.positive?
    dropped
  end

  private

  require "set"
  require "digest"

  Member = Struct.new(:name, :data)

  def key(member)
    "#{member.name}\0#{Digest::SHA1.hexdigest(member.data)}"
  end

  def members_of(path)
    bytes = File.binread(path)
    members = []
    table = nil
    pos = 8
    while pos + HEADER <= bytes.bytesize
      header = bytes.byteslice(pos, HEADER)
      break unless header.end_with?("`\n")

      size = header[48, 10].to_i
      nf = header[0, 16]
      stripped = nf.sub(/[\x00\s]+\z/, "")
      if stripped.start_with?("__.SYMDEF", "__.STRTAB") || stripped == "/"
        # symbol table — regenerated by ranlib on repack
      elsif stripped == "//"
        table = bytes.byteslice(pos + HEADER, size)
      elsif (m = nf.match(%r{\A#1/(\d+)}))
        len = m[1].to_i
        name = bytes.byteslice(pos + HEADER, len).split("\x00").first
        # The symbol table rides the BSD inline form too — skip it
        # (regenerated by ranlib on repack).
        unless name.start_with?("__.SYMDEF", "__.STRTAB")
          members << Member.new(name, bytes.byteslice(pos + HEADER + len, size - len))
        end
      elsif (m = stripped.match(%r{\A/(\d+)\z}))
        off = m[1].to_i
        name = table&.byteslice(off..)&.split("/", 2)&.first
        members << Member.new(name, bytes.byteslice(pos + HEADER, size)) if name
      else
        name = stripped.end_with?("/") ? stripped[0..-2] : stripped
        members << Member.new(name, bytes.byteslice(pos + HEADER, size))
      end
      pos += HEADER + size + (size.odd? ? 1 : 0)
    end
    members
  end

  def repack(path, kept)
    require "tmpdir"
    require "fileutils"
    Dir.mktmpdir do |dir|
      files = kept.each_with_index.map do |member, i|
        f = File.join(dir, format("%05d_%.56s", i, member.name))
        File.binwrite(f, member.data)
        f
      end
      FileUtils.rm_f(path)
      system(@ar, "rc", path, *files, exception: true)
      system(@ranlib, path, exception: true)
    end
  end
end
