# Copyright (c) 2023-2024 [Ribose Inc](https://www.ribose.com).
# All rights reserved.
# This file is a part of tamatebako
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

test_task_template: &TEST_TASK_TEMPLATE
  testset-1_script: |
    RUBY_VER=3.2.6 tests/scripts/functional-tests.sh

  testset-1-app_script: |
    RUBY_VER=3.3.6 MODE=app tests/scripts/functional-tests.sh

  testset-2_script: |
    RUBY_VER=3.2.6 ruby tests-2/tebako-test.rb

  checkout-packed-mn_script: |
    git clone https://github.com/metanorma/packed-mn.git packed-mn

  package-metanorma_script: |
    exe/tebako press -D --root=packed-mn --entry-point=bin/metanorma --output=metanorma-package -R 3.2.6

  smoke-test_script: |
    ./metanorma-package help

task:
  name: ubuntu-aarch64
  only_if: $CIRRUS_BRANCH == 'main' || $CIRRUS_PR != '' || $CIRRUS_TAG != ''
  arm_container:
# Needs ~10 Gb to package metanorma and Cirrus-ci allows 4GB per CPU only
    image: ubuntu:22.04
    cpu: 3
    memory: 12G

  env:
    CIRRUS_CLONE_SUBMODULES: true
    CIRRUS_CLONE_DEPTH: 1
    VERBOSE: no
    CMAKE_VERSION: 3.26.5
    CC: clang-12
    CXX: clang++-12
# { CC: gcc, CXX: g++ } commented to save Cirrus-ci limited capacity
# (clang is better both for performance and size)

  install_script: |
    DEBIAN_FRONTEND=noninteractive apt-get -y update
    DEBIAN_FRONTEND=noninteractive \
    apt-get -y install sudo git curl build-essential pkg-config bison flex autoconf \
      binutils-dev libevent-dev acl-dev libfmt-dev libjemalloc-dev libiberty-dev    \
      libdouble-conversion-dev liblz4-dev liblzma-dev libssl-dev libunwind-dev      \
      libboost-filesystem-dev libboost-program-options-dev libboost-system-dev      \
      libboost-iostreams-dev  libboost-date-time-dev libboost-context-dev           \
      libboost-regex-dev libboost-thread-dev libbrotli-dev libdwarf-dev libelf-dev  \
      libgoogle-glog-dev libffi-dev libgdbm-dev libyaml-dev libncurses-dev          \
      libreadline-dev libutfcpp-dev libncurses-dev libreadline-dev gcc-10 g++-10    \
      clang-12 clang++-12 ruby-dev ruby-bundler

  pre-setup_script: |
    cat common.env >> $CIRRUS_ENV
    SECURE_TMP_DIR="$PWD/secure_tmp"
    mkdir -p "$SECURE_TMP_DIR"
    chmod 700 "$SECURE_TMP_DIR"
    echo TMPDIR="$SECURE_TMP_DIR" >> $CIRRUS_ENV
    git clone --depth 1 https://github.com/kward/shunit2.git tests/shunit2

  setup-cmake_script: |
    mkdir -p cmake-install
    pushd cmake-install
    curl -L -o cmake.sh \
    https://github.com/Kitware/CMake/releases/download/v"$CMAKE_VERSION"/cmake-"$CMAKE_VERSION"-linux-aarch64.sh
    sudo sh cmake.sh --skip-license --prefix="/usr/local"
    popd

  pre-cache_script: |
    mkdir -p $DEPS

  tebako_cache:
    folder: $DEPS
    reupload_on_changes: false
    fingerprint_script:
      - echo $CIRRUS_OS
      - echo $CC
      - cat common.env
      - cat .cirrus.yml
      - cat lib/tebako/version.rb

# cirrus-ci hash does not work for optimized Ruby patching/build
# most likely it changes file times that causes make do a kind of
# 'random' rebuild
  setup_script: |
    bundle install
    exe/tebako clean_ruby
    exe/tebako setup -D -R 3.2.6

  upload_caches:
    - tebako

  << : *TEST_TASK_TEMPLATE
