# frozen_string_literal: true

brew "zlib"
brew "ncurses"
brew "libevent"
brew "libsodium"
brew "lz4"
brew "xz"
brew "gdbm"
brew "pkg-config"
brew "libyaml"
brew "curl"
brew "bison"
brew "flex"
brew "binutils"
brew "libffi"
brew "double-conversion"
brew "boost"
brew "jemalloc"
brew "fmt"
brew "glog"
brew "gnu-sed"
brew "bash"
brew "brotli"
