= Tebako: an image packager

image:https://github.com/tamatebako/tebako/actions/workflows/ubuntu.yml/badge.svg["Ubuntu", link="https://github.com/tamatebako/tebako/actions/workflows/ubuntu.yml"]
image:https://github.com/tamatebako/tebako/actions/workflows/macos.yml/badge.svg["MacOS", link="https://github.com/tamatebako/tebako/actions/workflows/macos.yml"]
image:https://github.com/tamatebako/tebako/actions/workflows/lint.yml/badge.svg["lint", link="https://github.com/tamatebako/tebako/actions/workflows/lint.yml"]


== Purpose

Tebako is an executable packager. It packages a set of files into a DwarFS file
system for read-only purposes.

After packaging the file system into an image, Tebako produces a single
executable binary that allows the user to execute a selected file from the
packaged software from a point in the file system.

The packaged binary should support:

* Packaging a default DwarFS image inside the binary
* Support signing of the binary on macOS (via notarization)

In the future:

* Downloading new DwarFS images to be stored in the local home directory
* Allowing loading multiple DwarFS images in a stacked way
* Supporting a COW mechanism that the newly written files are stored
  in a separate image that can be loaded on top of the read-only file systems.

== Supported platforms

The Tebako packager is tested on the following platforms:

* Linux: Ubuntu 18.04; Ubuntu 20.04
* macOS: macOS 10.15 (Catalina); macOS 11.0 (Monterey)
* Windows: TBD


== Prerequisites

=== Ubuntu

==== GNU C/C++ 9.x

If GNU C/C++ 9.x is not available as a default package, it can be set up as
follows.

[source,sh]
----
apt-get install -y software-properties-common
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get install gcc-9 g++-9

update-alternatives \
  --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 \
  --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
  --slave /usr/bin/gcov gcov /usr/bin/gcov-9
update-alternatives --set gcc /usr/bin/gcc-9
----

==== CMake version 3.20+

Tebako relies on CMake 3.20+, which may not be available as a default package.

If it is not available as default package it can be set up as follows:

[source,sh]
----
apt-get remove --purge --auto-remove cmake
apt-get update
apt-get install -y software-properties-common lsb-release curl
apt-get clean all
curl https://apt.kitware.com/kitware-archive.sh | bash
apt-get install cmake
----

==== libfmt version 6.0+

On Ubuntu 20 it can be installed with:

[source,sh]
----
apt-get install libfmt-dev
----

On Ubuntu 18 it requires a backport:

[source,sh]
----
apt-get -y remove libfmt-dev
apt-get -y install software-properties-common
add-apt-repository -a ppa:team-xbmc/ppa
apt-get -y update
apt-get -y install libfmt-dev
----

==== Other development tools and libraries

Ubuntu 18 and Ubuntu 20 default versions are good enough.

[source,sh]
----
apt-get install -y curl git ruby ruby-dev pkg-config bison flex make autoconf
apt-get install -y binutils-dev libarchive-dev libevent-dev libjemalloc-dev acl-dev \
  libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
  libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
  libboost-regex-dev libboost-system-dev libboost-thread-dev \
  libunwind-dev libdwarf-dev libelf-dev libfuse-dev libgoogle-glog-dev \
  libffi-dev libgdbm-dev libyaml-dev libncurses-dev libreadline-dev \
  libsqlite3-dev
----


== Installation

=== General

Just clone this repository, and run `tebako setup` as follows.

[source,sh]
----
git clone https://github.com/tamatebako/tebako
tebako/bin/tebako setup
----


=== Quick setup on Ubuntu 20.04 on Docker

Launch a container on the target platform:

[source,sh]
----
# For x86_64
docker run -it --platform linux/x86_64 ubuntu bash

# For Apple M1
docker run -it --platform linux/aarch64 ubuntu bash
----

In the container:

[source,sh]
----
export DEBIAN_FRONTEND=noninteractive
export TZ=Etc/UTC

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get install -y gcc-9 g++-9

update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
update-alternatives --set gcc /usr/bin/gcc-9

apt-get install -y curl git ruby ruby-dev pkg-config bison flex make autoconf
curl https://apt.kitware.com/kitware-archive.sh | bash
apt-get install -y cmake

apt-get install -y binutils-dev libarchive-dev libevent-dev libjemalloc-dev acl-dev \
  libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
  libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
  libboost-regex-dev libboost-system-dev libboost-thread-dev \
  libunwind-dev libdwarf-dev libelf-dev libfuse-dev libgoogle-glog-dev \
  libffi-dev libgdbm-dev libyaml-dev libncurses-dev libreadline-dev \
  libsqlite3-dev

apt-get install -y libfmt-dev

git clone https://github.com/tamatebako/tebako
tebako/bin/tebako setup
----


== Usage

=== Commands

==== Setup

[source,sh]
----
<install-folder>/bin/tebako setup [-p |--prefix=<tebako-root-folder>] 
                                  [-t|--target=[guess|arm64-apple-macos11|x86_64-apple-macos11]
                                  [-b|--target-homebrew=<homebrew for target architecture>]
----

Collect and builds Tebako packager and install them for Tebako packager at
`<tebako root folder>` (defaults to the install folder).

Cross-compile options:
target: setting this value to anything except 'guess' activates cross-compilation. 
        Valid values are: arm64-apple-macos11 or x86_64-apple-macos11.  
target-homebrew: the directory where homebrew for target architecture is installed

Tebako supports several configurations at a single system given that their root
directories differ.

=== Press

This command "presses" a Ruby project using the Tebako setup from the Tebako root
folder (`<tebako-root-folder>`).

[source,sh]
----
<install-folder>/bin/tebako press      \
  [-p | --prefix=<tebako-root-folder>] \
   -r | --root=<project-root-folder>   \
   -e | --entry-point=<entry-point>    \
  [-o | --output=<packaged file name>] \
  [-t | --target=[guess|arm64-apple-macos11|x86_64-apple-macos11]  \
  [-b | --target-homebrew=<homebrew for target architecture>]
----

Where:

* `<tebako-root-folder>`, the Tebako setup folder (optional, defaults to current
folder)

* `<project-root>`, a folder at the host source file system where project files
are located

* `<entry-point>`, an executable file (binary executable or script) that shall
be started when packaged file is called

* `output`, the output file name (optional, defaults to `<current folder>/<entry
point base name`)


[example]
====
[source,sh]
----
bin/tebako press \
  --root='~/projects/myproject' \
  --entry=start.rb \
  --output=/temp/myproject.tebako
----
====

=== Clean

This command deletes tebako artifacts created by setup and press commands.
Normally you do not need to do it since tebako packager optimizes artifacts lifecycle on its own.

[source,sh]
----
bin/tebako press \
  [-p |--prefix=<tebako-root-folder>]
----

Where:

* `<tebako-root-folder>`, the Tebako setup folder (optional, defaults to current
folder)

[example]
====
[source,sh]
----
bin/tebako clean --root='~/projects/myproject'
----
====

=== Exit codes

[cols,"a,a"]
|===
| Code | Condition

| 0    | No error
| 1    | `getopts` not supported by OS
| 2    | Failed to parse command line
| 3    | Internal error
| 4    | Missing command (`setup` or `press` is required)
| 5    | `tebako press` without mandatory `--root` option
| 6    | `tebako press` without mandatory `--entry-point` option
| 7    | Unsupported operating system
| 8    | Could not find gnu getopts     
| 9    | Cross compilation is supported on MacOS only
| 10   | Invalid target option. Valid options are: 'arm64-apple-macos11' or 'x86_64-apple-macos11'
| 11   | Invalid log level. Known values are 'error', 'warn', 'debug', 'trace'
| 101  | `tebako setup` failed at configuration step
| 102  | `tebako setup` failed at build step
| 103  | `tebako press` failed at configuration step
| 104  | `tebako press` failed at build step

|===


== Ruby packaging specification

This is high-level description of the Tebako Ruby packaging mechanism.
This specification was inspired by the `ruby-packer` approach.

NOTE: For various reasons, Tebako Ruby is a fully separate implementation,
no line of code was copied from `ruby-packer`.

Depending on the configuration files that are present in the root project folder,
the Tebako Ruby packager support five different scenarios:

[cols="a,a,a,a"]
|===
| Scenario | `*.gemspec` | `Gemfile`  | `*.gem`

| 1        |     No    |   No     |   No
| 2        |     No    |   No     |   One
| 3        |    One    |   No     |   Any
| 4        |    One    |   One    |   Any
| 5        |     No    |   One    |   Any
| Error    |     No    |   No     |Two or more
| Error    |Two or more|   Any    |   Any

|===

These scenarios differ in what files are packaged and where the entry point is
located, as follows:

[cols="a,a,a,a"]
|===
| Scenario | Description | Packaging | Entry point

| 1
| Simple ruby script
| Copy `<project-root>` with all sub-folders to packaged filesystem
| `<mount_point>/local/<entry_point base name>`

| 2
| Packaged gem
| Install the gem with `gem install` to packaged filesystem
| `<mount_point>/bin/<entry_point base name>` (i.e., binstub is expected)

| 3
| Gem source, no `bundler`
|
. Build the gem using `gem build` command at the host
. Install it with `gem install` to packaged filesystem

| `<mount_point>/bin/<entry_point base name>` (i.e., binstub is expected)

| 4
| Gem source, `bundler`
|
. Collect dependencies at the host with `bundle install`
. Build the gem using `gem build` command
. Install it with `gem install` to packaged file system

| `<mount_point>/bin/<entry_point base name>` (i.e., binstub is expected)

| 5
| Rails project
| Deploy project to packaged filesystem using `bundle install`
| `<mount_point>/local/<entry_point base name>`

|===


== Trivia: origin of name

"tamatebako" (玉手箱) is the treasure box given to Urashima Taro in the Ryugu,
for which he was asked not to open if he wished to return. He opened the box
upon the shock from his return that three hundred years has passed. Apparently
what was stored in the box was his age.

This packager was made to store Ruby and its gems, and therefore named after
the said treasure box (storing gems inside a treasure box).

Since "tamatebako" is rather long for the non-Japanese speaker, we use "tebako"
(手箱, also "tehako") instead, the generic term for a personal box.

