# frozen_string_literal: true

source "https://rubygems.org"

gem "bundler" # rubocop:disable Gemspec/DevelopmentDependencies
gem "ffi" # rubocop:disable Gemspec/DevelopmentDependencies
gem "seven-zip", "~>1.4"
