# Copyright (c) 2023-2024 [Ribose Inc](https://www.ribose.com).
# All rights reserved.
# This file is a part of the Tebako project.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

name: 'Test: Package metanorma'
description: 'Test: Package metanorma using locally deployed tebako gem'
inputs:
  upload:
    description: 'Upload arfifacts for tests on other OS version'
    required: true
    type: string
    default: 'false'
  verbose:
    description: Enable verbose output
    required: false
    default: 'no'
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout shell test framework
      uses: actions/checkout@v4
      with:
        repository: kward/shunit2
        path: ${{github.workspace}}/tests/shunit2
        fetch-depth: 1

    - name: Run tebako tests (set no. 1)
      shell: bash
      run: |
        bundle install
        VERBOSE=${{ inputs.verbose }} RUBY_VER=${{ matrix.package_ruby_ver }} tests/scripts/functional-tests.sh

    - name: Strip tebako test packages
      if: ${{ !contains(matrix.env.os, 'macos') && inputs.upload == 'true' }}
      shell: bash
      run: strip *-package

    - name: Upload tebako test packages
      if: ${{ inputs.upload == 'true'}}
      uses: actions/upload-artifact@v4
      with:
        name: test-packages
        retention-days: 1
        path: |
          test-01-package
          test-11-package
          test-15-package
          test-18-package
          test-19-package
          test-20-package
          test-21-package
