// autogenerated code, do not modify

#include "dwarfs/version.h"

namespace dwarfs {

char const* PRJ_GIT_REV = "78fd324";
char const* PRJ_GIT_DESC = "v0.5.6";
char const* PRJ_GIT_BRANCH = "metanorma/main";
char const* PRJ_GIT_ID = "v0.5.6";

} // namespace dwarfs