// autogenerated code, do not modify

#pragma once

#define PRJ_VERSION_MAJOR 0
#define PRJ_VERSION_MINOR 5
#define PRJ_VERSION_PATCH 6

namespace dwarfs {

extern char const* PRJ_GIT_REV;
extern char const* PRJ_GIT_DESC;
extern char const* PRJ_GIT_BRANCH;
extern char const* PRJ_GIT_ID;

} // namespace dwarfs