// autogenerated code, do not modify

#include "dwarfs/version.h"

namespace dwarfs {

char const* PRJ_GIT_REV = "2a51edb";
char const* PRJ_GIT_DESC = "v0.5.6";
char const* PRJ_GIT_BRANCH = "main";
char const* PRJ_GIT_ID = "v0.5.6";

} // namespace dwarfs