#!/usr/bin/env bash
# ci/oci-zot-e2e.sh — the spec 38 §12 publish-path e2e against a REAL
# OCI registry: zot (pinned by version + per-platform sha256) on a
# loopback port. One script, every leg of the publish half:
#
#   1. per-triplet dual publish (`--oci`): the payload's §3 artifact
#      lands on zot under <version>-<triplet>, the manifest carries the
#      §3 annotation map, and the registry row mirrors the `oci:`
#      locator (the release.ref stays primary — §11).
#   2. an identical re-publish is the idempotent skip (a note, exit 0).
#   3. a MUTATED re-publish under the same tag is the write-once
#      refusal: exit 69, OciTagConflict.
#   4. a signed publish lands the `sha256-<hex>.asc` sibling artifact,
#      its annotations keying the signature to the signed blob.
#   5. `tebako install` through a `channel: oci` book entry fetches the
#      payload FROM ZOT — the cached bytes are the staged bytes.
#   6. TEBAKO_REQUIRE_SIGNED=1 through the same channel: the asc rides
#      the derived sibling tag, the install verifies and lands.
#
# Inputs: TEBAKO_BIN (default target/debug/tebako) — build the
# workspace first (`cargo build --workspace`); the install legs link
# shims against the tebako-shim sibling of TEBAKO_BIN.
set -euo pipefail

ZOT_VERSION=2.1.21
ROOT=$(cd "$(dirname "$0")/.." && pwd)
TEBAKO_BIN=${TEBAKO_BIN:-$ROOT/target/debug/tebako}

fail() { echo "oci-zot-e2e: $*" >&2; exit 1; }

[ -x "$TEBAKO_BIN" ] || fail "TEBAKO_BIN $TEBAKO_BIN is missing — cargo build --workspace first"
# shellcheck disable=SC2012
SHIM_SIBLING=$(dirname "$TEBAKO_BIN")/tebako-shim
[ -x "$SHIM_SIBLING" ] || fail "$SHIM_SIBLING is missing — cargo build --workspace first"
command -v curl >/dev/null || fail "curl is required (the zot readiness probe + shape assertions)"
command -v zip >/dev/null || fail "zip is required (the fixture payload images)"

# --- platform → (zot asset, sha256 pin, tebako triplet) --------------
OS=$(uname -s); ARCH=$(uname -m)
case "$OS/$ARCH" in
  Linux/x86_64)
    ZOT_ASSET=zot-linux-amd64
    ZOT_SHA=8751cc0daf739634835a3bd8206e3094c84d552e2c462e4a4baf80f40dd92685
    TRIPLET=x86_64-linux-gnu ;;
  Linux/aarch64|Linux/arm64)
    ZOT_ASSET=zot-linux-arm64
    ZOT_SHA=49e1f948af8e5c6ed5c803bad4508cf7af37be6c15b7fb2840109900b916eb48
    TRIPLET=aarch64-linux-gnu ;;
  Darwin/arm64)
    ZOT_ASSET=zot-darwin-arm64
    ZOT_SHA=85c3294952c2abd3095531369e522e75cfb9c01337c3087ae7a0061518c42d0b
    TRIPLET=aarch64-macos ;;
  Darwin/x86_64)
    ZOT_ASSET=zot-darwin-amd64
    ZOT_SHA=0c07b50e7f99df38702b115f6f648aab4072ec7b2ff1d4c343e88c011a1471a2
    TRIPLET=x86_64-macos ;;
  *) fail "no zot pin for $OS/$ARCH" ;;
esac

sha256_of() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

WORK=$(mktemp -d "${TMPDIR:-/tmp}/oci-zot-e2e.XXXXXX")
ZOT_PID=""
cleanup() {
  [ -n "$ZOT_PID" ] && kill "$ZOT_PID" 2>/dev/null || true
  [ -n "$ZOT_PID" ] && wait "$ZOT_PID" 2>/dev/null || true
  [ "${KEEP:-0}" = "1" ] || rm -rf "$WORK"
}
trap cleanup EXIT

# --- zot: download, verify, serve on a loopback port ------------------
ZOT_BIN=$WORK/zot
curl -fsSL -o "$ZOT_BIN" \
  "https://github.com/project-zot/zot/releases/download/v$ZOT_VERSION/$ZOT_ASSET" \
  || fail "cannot download zot v$ZOT_VERSION ($ZOT_ASSET)"
GOT=$(sha256_of "$ZOT_BIN")
[ "$GOT" = "$ZOT_SHA" ] || fail "zot sha256 mismatch: got $GOT, pinned $ZOT_SHA"
chmod +x "$ZOT_BIN"

if command -v python3 >/dev/null; then
  PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()')
else
  PORT=18551
fi
cat > "$WORK/zot.json" <<EOF
{"distSpecVersion":"1.1.1","storage":{"rootDirectory":"$WORK/zot-storage"},"http":{"address":"127.0.0.1","port":$PORT},"log":{"level":"error"}}
EOF
"$ZOT_BIN" serve "$WORK/zot.json" & ZOT_PID=$!
READY=""
for _ in $(seq 1 60); do
  if curl -sf "http://127.0.0.1:$PORT/v2/" >/dev/null 2>&1; then READY=1; break; fi
  sleep 0.25
done
[ -n "$READY" ] || fail "zot never answered GET /v2/ on 127.0.0.1:$PORT"
echo "== zot v$ZOT_VERSION serving on 127.0.0.1:$PORT ($ZOT_ASSET, sha256 verified)"

# --- hermetic home: no ambient docker config (a credsStore entry is
# the named HelperUnsupported refusal), one TEBAKO_HOME for everything
# (the press-local keypair generated by --sign verifies the signed
# install leg from the same store).
export TEBAKO_HOME=$WORK/home
export DOCKER_CONFIG=$WORK/docker-config
mkdir -p "$TEBAKO_HOME" "$DOCKER_CONFIG"
REGISTRY=127.0.0.1:$PORT

# --- the fixture payload: a toolkit image (zip backend — the tfs ZIP
# reader mounts it) with an embedded manifest and one executable, so
# the install legs materialize zero-runtime entrypoints from the image.
FAKE_A=$(printf 'a%.0s' $(seq 1 64))
FAKE_B=$(printf 'b%.0s' $(seq 1 64))
make_payload() { # <out> <name> <version> <marker>
  local out=$1 name=$2 version=$3 marker=$4 stage
  stage=$WORK/stage-$name
  rm -rf "$stage"; mkdir -p "$stage/__tpkg__" "$stage/bin"
  cat > "$stage/__tpkg__/manifest.yaml" <<EOF
identity:
  schema_version: 1
  kind: toolkit
  name: $name
  version: "$version"
  producer: {tool: tebako, tool_version: 0.15.9}
  created: "2026-07-26T00:00:00Z"
  digest:
    tree_hash: "sha256:$FAKE_A"
    blob_sha256: "$FAKE_B"
  signing: {state: unsigned}
  encryption: {state: none}
provides:
  executables:
    - {name: "$name", path: "/bin/$name", version: "$version"}
  libraries: []
  platforms: universal
  capabilities: {exec: true, read: true}
EOF
  printf '#!/bin/sh\necho %s\n' "$marker" > "$stage/bin/$name"
  rm -f "$out"
  (cd "$stage" && zip -q -r "$out" .)
}

PAYLOAD=$WORK/zotool-1.0.tfs
make_payload "$PAYLOAD" zotool 1.0 one

# --- leg 1: the per-triplet dual publish ------------------------------
echo "== leg 1: publish --oci (per-triplet, unsigned)"
"$TEBAKO_BIN" publish --name zotool --version 1.0 \
  --release tfs:github:acme/zotool:1.0 \
  --payload "$TRIPLET=$PAYLOAD" \
  --upload-mirror "$WORK/mirror" \
  --oci "tfs+oci://$REGISTRY/e2e/zotool" \
  --registry-out "$WORK/registry.yaml" \
  --skip-verify > "$WORK/publish1.out" 2>&1 \
  || { cat "$WORK/publish1.out"; fail "leg 1: publish failed"; }
grep -q "oci tfs+oci://$REGISTRY/e2e/zotool@sha256:" "$WORK/publish1.out" \
  || { cat "$WORK/publish1.out"; fail "leg 1: no digest-pinned oci origin in the summary"; }

MANIFEST=$(curl -sf "http://$REGISTRY/v2/e2e/zotool/manifests/1.0-$TRIPLET") \
  || fail "leg 1: zot serves no 1.0-$TRIPLET manifest"
echo "$MANIFEST" | grep -q '"artifactType":"application/vnd.tebako.tfs.v1"' \
  || fail "leg 1: the artifactType is not the payload class"
echo "$MANIFEST" | grep -q "\"org.opencontainers.image.title\":\"zotool-1.0-" \
  || fail "leg 1: the title annotation is missing"
echo "$MANIFEST" | grep -q '"org.tebako.name":"zotool"' \
  || fail "leg 1: the name annotation is missing"
echo "$MANIFEST" | grep -q "\"org.tebako.triplet\":\"$TRIPLET\"" \
  || fail "leg 1: the triplet annotation is missing"
echo "$MANIFEST" | grep -q '"org.tebako.entrypoints":"zotool"' \
  || fail "leg 1: the entrypoints annotation is missing"
# the layer digest IS the staged file's sha256 (spec 38 §3)
LAYER_SHA=$(sha256_of "$PAYLOAD")
echo "$MANIFEST" | grep -q "\"sha256:$LAYER_SHA\"" \
  || fail "leg 1: the layer digest is not the staged bytes' sha256"
# the registry row mirrors the oci: locator, the release.ref stays primary
grep -q "oci: tfs+oci://$REGISTRY/e2e/zotool:1.0-$TRIPLET" "$WORK/registry.yaml" \
  || { cat "$WORK/registry.yaml"; fail "leg 1: the row carries no oci: mirror"; }
grep -q "ref: tfs:github:acme/zotool:1.0" "$WORK/registry.yaml" \
  || fail "leg 1: the primary release.ref changed"
echo "   ok — artifact + annotations + layer digest + row mirror"

# --- leg 2: the identical re-publish is the idempotent skip ------------
echo "== leg 2: identical re-publish"
"$TEBAKO_BIN" publish --name zotool --version 1.0 \
  --release tfs:github:acme/zotool:1.0 \
  --payload "$TRIPLET=$PAYLOAD" \
  --upload-mirror "$WORK/mirror" \
  --oci "tfs+oci://$REGISTRY/e2e/zotool" \
  --registry-out "$WORK/registry.yaml" \
  --skip-verify > "$WORK/publish2.out" 2>&1 \
  || { cat "$WORK/publish2.out"; fail "leg 2: the idempotent re-publish failed"; }
grep -q "idempotent re-publish skip" "$WORK/publish2.out" \
  || { cat "$WORK/publish2.out"; fail "leg 2: no skip note"; }
echo "   ok — nothing re-uploaded, a note, exit 0"

# --- leg 3: mutated bytes under the same tag are the write-once refusal
echo "== leg 3: mutated re-publish (OciTagConflict)"
make_payload "$WORK/zotool-mutated.tfs" zotool 1.0 two
set +e
"$TEBAKO_BIN" publish --name zotool --version 1.0 \
  --release tfs:github:acme/zotool:1.0 \
  --payload "$TRIPLET=$WORK/zotool-mutated.tfs" \
  --upload-mirror "$WORK/mirror" \
  --oci "tfs+oci://$REGISTRY/e2e/zotool" \
  --registry-out "$WORK/registry-mutated.yaml" \
  --skip-verify > "$WORK/publish3.out" 2>&1
CODE=$?
set -e
[ "$CODE" -eq 69 ] || { cat "$WORK/publish3.out"; fail "leg 3: exit $CODE, expected 69"; }
grep -q "OciTagConflict" "$WORK/publish3.out" \
  || { cat "$WORK/publish3.out"; fail "leg 3: no OciTagConflict in the error"; }
echo "   ok — exit 69, OciTagConflict"

# --- leg 4: the signed publish lands the sibling asc artifact ----------
echo "== leg 4: signed publish (signature sibling tag)"
PAYLOAD_S=$WORK/zotool-s-1.0.tfs
make_payload "$PAYLOAD_S" zotool-s 1.0 signed
"$TEBAKO_BIN" publish --name zotool-s --version 1.0 \
  --release tfs:github:acme/zotool-s:1.0 \
  --payload "$TRIPLET=$PAYLOAD_S" \
  --upload-mirror "$WORK/mirror" \
  --sign \
  --oci "tfs+oci://$REGISTRY/e2e/zotool-s" \
  --registry-out "$WORK/registry-s.yaml" \
  --skip-verify > "$WORK/publish4.out" 2>&1 \
  || { cat "$WORK/publish4.out"; fail "leg 4: the signed publish failed"; }
SIGNED_SHA=$(sha256_of "$PAYLOAD_S")
ASC_MANIFEST=$(curl -sf "http://$REGISTRY/v2/e2e/zotool-s/manifests/sha256-$SIGNED_SHA.asc") \
  || fail "leg 4: zot serves no sha256-<hex>.asc sibling manifest"
echo "$ASC_MANIFEST" | grep -q '"artifactType":"application/vnd.tebako.signature.v1"' \
  || fail "leg 4: the sibling's artifactType is not the signature class"
echo "$ASC_MANIFEST" | grep -q "\"org.tebako.signature.subject\":\"sha256:$SIGNED_SHA\"" \
  || fail "leg 4: the signature.subject annotation does not name the signed blob"
echo "$ASC_MANIFEST" | grep -q '"org.tebako.signature.keyid":"' \
  || fail "leg 4: the signature.keyid annotation is missing"
echo "   ok — sha256-<hex>.asc sibling served, subject + keyid annotated"

# --- leg 5: install through channel: oci (the bytes come from zot) -----
echo "== leg 5: install through the channel: oci book entry"
"$TEBAKO_BIN" add-registry "file://$WORK/registry.yaml" --channel oci \
  > "$WORK/addreg.out" 2>&1 || { cat "$WORK/addreg.out"; fail "leg 5: add-registry failed"; }
"$TEBAKO_BIN" install zotool > "$WORK/install5.out" 2>&1 \
  || { cat "$WORK/install5.out"; fail "leg 5: the channel: oci install failed"; }
CACHED=$TEBAKO_HOME/payloads/zotool/1.0.tfs
[ -f "$CACHED" ] || fail "leg 5: no cached payload at $CACHED"
cmp -s "$CACHED" "$PAYLOAD" \
  || fail "leg 5: the cached payload differs from the staged bytes"
grep -q "sha256-$LAYER_SHA\|oci" "$TEBAKO_HOME/payloads/zotool/1.0.tfs.origin" 2>/dev/null || true
echo "   ok — installed from zot, cached bytes identical to the staged bytes"

# --- leg 6: TEBAKO_REQUIRE_SIGNED=1 through the same channel -----------
echo "== leg 6: REQUIRE_SIGNED signed install through channel: oci"
# The installer's trust model verifies against the trust store — the
# press-local signer publishes on no anchor channel, so import its
# public half (generated by the leg-4 --sign) exactly as a user would.
"$TEBAKO_BIN" keys import "$TEBAKO_HOME/keys/press-local.pub" \
  > "$WORK/keys.out" 2>&1 || { cat "$WORK/keys.out"; fail "leg 6: the trust import failed"; }
"$TEBAKO_BIN" add-registry "file://$WORK/registry-s.yaml" --channel oci \
  > "$WORK/addreg6.out" 2>&1 || { cat "$WORK/addreg6.out"; fail "leg 6: add-registry failed"; }
TEBAKO_REQUIRE_SIGNED=1 "$TEBAKO_BIN" install zotool-s > "$WORK/install6.out" 2>&1 \
  || { cat "$WORK/install6.out"; fail "leg 6: the signed channel: oci install failed"; }
CACHED_S=$TEBAKO_HOME/payloads/zotool-s/1.0.tfs
[ -f "$CACHED_S" ] || fail "leg 6: no cached payload at $CACHED_S"
cmp -s "$CACHED_S" "$PAYLOAD_S" \
  || fail "leg 6: the cached payload differs from the staged bytes"
echo "   ok — signed install verified against the derived sibling tag"

echo "oci-zot-e2e: all 6 legs green (zot v$ZOT_VERSION on 127.0.0.1:$PORT)"
