# frozen_string_literal: true

source "https://rubygems.org"

gem "bundler", "~> 2.4.0"
gem "expressir" # rubocop:disable Gemspec/DevelopmentDependencies
gem "ffi" # rubocop:disable Gemspec/DevelopmentDependencies
