if(NOT WIN32)
  string(ASCII 27 Escape)
  set(ColourReset       "${Escape}[m")
  set(ColourBold        "${Escape}[1m")
  set(ColourRed         "${Escape}[31m")
  set(ColourGreen       "${Escape}[32m")
  set(ColourYellow      "${Escape}[33m")
  set(ColourBlue        "${Escape}[34m")
  set(ColourMagenta     "${Escape}[35m")
  set(ColourCyan        "${Escape}[36m")
  set(ColourWhite       "${Escape}[37m")
  set(ColourBoldRed     "${Escape}[1;31m")
  set(ColourBoldGreen   "${Escape}[1;32m")
  set(ColourBoldYellow  "${Escape}[1;33m")
  set(ColourBoldBlue    "${Escape}[1;34m")
  set(ColourBoldMagenta "${Escape}[1;35m")
  set(ColourBoldCyan    "${Escape}[1;36m")
  set(ColourBoldWhite   "${Escape}[1;37m")
endif()